# Generated by Django 3.2.3 on 2021-07-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='user_response',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
