# Generated by Django 3.2.3 on 2021-07-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_meetup_user_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='quiz',
            field=models.ManyToManyField(to='demo.Quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(default='0000000', editable=False, max_length=1000),
        ),
    ]
