# Generated by Django 3.2.4 on 2021-07-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_alter_quiz_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='answer',
            new_name='answer1',
        ),
        migrations.AddField(
            model_name='reply',
            name='answer2',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='answer3',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
