# Generated by Django 3.2.4 on 2021-07-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_participant_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reply',
            name='answer1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='answer2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='answer3',
            field=models.TextField(null=True),
        ),
    ]
