# Generated by Django 3.2.4 on 2021-07-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_auto_20210726_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
