# Generated by Django 3.2.4 on 2021-07-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_participant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='reply',
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer3',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
